# Generated by Django 4.1.3 on 2022-11-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_transaction_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='author',
            new_name='username',
        ),
    ]
