# Generated by Django 4.1.3 on 2022-11-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_author_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='username',
        ),
    ]
