# Generated by Django 4.1.3 on 2022-11-25 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_remove_money_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='desc',
            field=models.CharField(default='Rent', max_length=20),
        ),
        migrations.AddField(
            model_name='money',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
