# Generated by Django 4.1.3 on 2022-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_money_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
