# Generated by Django 4.1.3 on 2022-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_money_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
