# Generated by Django 4.1.3 on 2022-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='available',
            field=models.IntegerField(),
        ),
    ]
