# Generated by Django 4.1.3 on 2022-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bedsitter_onebedroom_delete_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onebedroom',
            name='room',
            field=models.CharField(default='OneBedroom', max_length=20),
        ),
    ]
